### ISSUE TITLE
filter and reject functions need to have 2 arguments?

### ISSUE THREAD

**Issue by Poetro** [eriwen/smap.js#3]
Why do `filter` and `reject` functions need to have 2 arguments? If i just want to filter on the key, or want to make a separate logic, and don't want to have any arguments at all? And also as I see, `iterate` gives 3 parameters to the callback function, why not pass all of them to the `filter` and `reject` and also pass the map itself. 

``` javascript
        this.iterate(function(key, value) {
            if(filterFn.apply(_map, arguments)) {
                _map.set(key, value);
            }
        });
```

**Comment by eriwen** [comment]
I agree completely, good call.
